<?php
function moviedb_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'moviedb/moviedb_css';
}

function moviedb_theme($existing, $type, $theme, $path) {
  return array(
    'article_list' => array(
      'variables' => array('items' => array(), 'form' => '', 'title' => '')
    ),
    'actormovie_list' => array(
      'variables' => array('items' => array(), 'title' => '')
    ),
    'actors_list' => array(
      'variables' => array('items' => array(), 'title' => '')
    ),
  );
}
